config/routes.rb
Planarias::Application.routes.draw do
  get "exportar/alternativas_especies"

  resources :membros





  resources :artigos

  resources :alternativas

  resources :caracteristicas

  resources :especie_imagens

  resources :especies

  resources :municipios

  resources :estados

  resources :paises

  resources :alternativas_especies

  resources :verespecie

  resources :verespecie_imagem
  
  resources :usuarios

  resources :generos
  
  resources :familias
  
  resources :subfamilias  
  




  root :to => 'home#index'


  match ':controller(/:action(/:id(.:format)))'
end

app/models/subfamilia.rb
# -*- encoding : utf-8 -*-
class Subfamilia < ActiveRecord::Base

  belongs_to :familia
  has_many :generos

  validates :nome, :presence => true, :uniqueness => true
  validates :familia_id, :presence => true
  
end

app/controllers/subfamilias_controller.rb
# -*- encoding : utf-8 -*-
class SubfamiliasController < ApplicationController
  # GET /subfamilias
  # GET /subfamilias.xml
  def index
    @subfamilias = Subfamilia.find(:all, :include => [:familia], :order => "familias.nome, subfamilias.nome")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subfamilias }
    end
  end

  # GET /subfamilias/1
  # GET /subfamilias/1.xml
  def show
    @subfamilia = Subfamilia.find(params[:id])
    @familia = Familia.find(@subfamilia.familia_id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subfamilia }
    end
  end

  # GET /subfamilias/new
  # GET /subfamilias/new.xml
  def new
    @subfamilia = Subfamilia.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subfamilia }
    end
  end

  # GET /subfamilias/1/edit
  def edit
    @subfamilia = Subfamilia.find(params[:id])
  end

  # POST /subfamilias
  # POST /subfamilias.xml
  def create
    @subfamilia = Subfamilia.new(params[:subfamilia])

    respond_to do |format|
      if @subfamilia.save
        flash[:notice] = 'Subfamília foi criado(a) com sucesso.'
        format.html { redirect_to(@subfamilia) }
        format.xml  { render :xml => @subfamilia, :status => :created, :location => @subfamilia }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subfamilia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subfamilias/1
  # PUT /subfamilias/1.xml
  def update
    @subfamilia = Subfamilia.find(params[:id])

    respond_to do |format|
      if @subfamilia.update_attributes(params[:subfamilia])
        flash[:notice] = 'Subfamília foi atualizado(a) com sucesso.'
        format.html { redirect_to(@subfamilia) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subfamilia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subfamilias/1
  # DELETE /subfamilias/1.xml
  def destroy
    @subfamilia = Subfamilia.find(params[:id])
    @generos = @subfamilia.generos

    @destroyed = false
    if @generos.first.nil?
      @subfamilia.destroy
      @destroyed = true
    end

    respond_to do |format|
      if @destroyed
        flash[:notice] = 'Subfamília excluído com sucesso.'
      else
        flash[:notice] = 'O subfamília não pode ser excluído devido a relação com o gênero ' + @generos.first.nome
      end
      format.html { redirect_to(subfamilias_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/subfamilias_helper.rb
# -*- encoding : utf-8 -*-
module SubfamiliasHelper
end

app/views/subfamilias/edit.html.erb
<h1>Editando subfamília</h1>

<%= form_for(@subfamilia) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :familia_id %><br />
    <%= @familias = Familia.find(:all, :order => "nome" )
        f.collection_select(:familia_id, @familias, :id, :nome)%>
  </p>
  <p>
    <%= f.submit 'Atualizar' %>
  </p>
<% end %>

<%= link_to 'Ver', @subfamilia %> |
<%= link_to 'Voltar', subfamilias_path %>

app/views/subfamilias/index.html.erb
<h1>Listando subfamílias</h1>

<% if @subfamilias.size.zero? %>
  <br />
  <p> Nenhuma subfamília cadastrada.</p>
<% else %>

  <table>
  <tr>
    <th>Família</th>
    <th>Subfamília</th>
  </tr>

<% @subfamilias.each do |subfamilia| %>
  <tr>
    <td><%=h subfamilia.familia.nome %></td>
    <td><%=h subfamilia.nome %></td>
    <td><%= link_to 'Ver', subfamilia %></td>
    <td><%= link_to 'Editar', edit_subfamilia_path(subfamilia) %></td>
    <td><%= button_to 'Excluir', subfamilia, :confirm => 'Você tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%end%>
<br />

<%= link_to 'Criar subfamília', new_subfamilia_path %>

app/views/subfamilias/new.html.erb
<h1>Nova subfamília</h1>

<%= form_for(@subfamilia) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :familia_id %><br />
    <%= @familias = Familia.find(:all, :order => "nome" )
        f.collection_select(:familia_id, @familias, :id, :nome)%>
  </p>
  <p>
    <%= f.submit 'Criar' %>
  </p>
<% end %>

<%= link_to 'Voltar', subfamilias_path %>

app/views/subfamilias/show.html.erb
<p>
  <b>Nome:</b>
  <%=h @subfamilia.nome %>
</p>

<p>
  <b>Família:</b>
  <%=h @familia.nome %>
</p>


<%= link_to 'Editar', edit_subfamilia_path(@subfamilia) %> |
<%= link_to 'Voltar', subfamilias_path %>