config/routes.rb
Planarias::Application.routes.draw do
  get "exportar/alternativas_especies"

  resources :membros





  resources :artigos

  resources :alternativas

  resources :caracteristicas

  resources :especie_imagens

  resources :especies

  resources :municipios

  resources :estados

  resources :paises

  resources :alternativas_especies

  resources :verespecie

  resources :verespecie_imagem
  
  resources :usuarios

  resources :generos
  
  resources :familias
  
  resources :subfamilias  
  




  root :to => 'home#index'


  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/paises_controller.rb
# -*- encoding : utf-8 -*-
class PaisesController < ApplicationController
  # GET /paises
  # GET /paises.xml
  def index
    @paises = Pais.find(:all, :order => "nome")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @paises }
    end
  end

  # GET /paises/1
  # GET /paises/1.xml
  def show
    @pais = Pais.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pais }
    end
  end

  # GET /paises/new
  # GET /paises/new.xml
  def new
    @pais = Pais.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pais }
    end
  end

  # GET /paises/1/edit
  def edit
    @pais = Pais.find(params[:id])
  end

  # POST /paises
  # POST /paises.xml
  def create
    @pais = Pais.new(params[:pais])

    respond_to do |format|
      if @pais.save
        flash[:notice] = 'País foi criado com sucesso.'
        format.html { redirect_to(@pais) }
        format.xml  { render :xml => @pais, :status => :created, :location => @pais }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pais.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /paises/1
  # PUT /paises/1.xml
  def update
    @pais = Pais.find(params[:id])

    respond_to do |format|
      if @pais.update_attributes(params[:pais])
        flash[:notice] = 'País foi atualizado com sucesso.'
        format.html { redirect_to(@pais) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pais.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /paises/1
  # DELETE /paises/1.xml
  def destroy
    @pais = Pais.find(params[:id])
    @estados = @pais.estados

    @destroyed = false
    if @estados.first.nil?
      @pais.destroy
      @destroyed = true
    end

    respond_to do |format|
      if @destroyed
        flash[:notice] = 'País excluído com sucesso.'
      else
        flash[:notice] = 'O país não pode ser excluído devido a relação com o estado ' + @estados.first.nome
      end
      format.html { redirect_to(paises_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/paises_helper.rb
# -*- encoding : utf-8 -*-
module PaisesHelper
end

app/views/paises/edit.html.erb
<h1>Editando país</h1>

<%= form_for(@pais) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.submit 'Atualizar' %>
  </p>
<% end %>

<%= link_to 'Ver', @pais %> |
<%= link_to 'Voltar', paises_path %>

app/views/paises/index.html.erb
<h1>Listando países</h1>

<% if @paises.size.zero? %>
  <br />
  <p> Nenhum país cadastrado.</p>
<% else %>

<table>
  <tr>
    <th>Nome</th>
  </tr>

<% @paises.each do |pais| %>
  <tr>
    <td><%=h pais.nome %></td>
    <td><%= link_to 'Ver', pais %></td>
    <td><%= link_to 'Editar', edit_pais_path(pais) %></td>
    <td><%= button_to 'Excluir', pais, :confirm => 'Você tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%end%>
  
<br />

<%= link_to 'Criar país', new_pais_path %>

app/views/paises/new.html.erb
<h1>Criar país</h1>

<%= form_for(@pais) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.submit 'Criar' %>
  </p>
<% end %>

<%= link_to 'Voltar', paises_path %>

app/views/paises/show.html.erb
<p>
  <b>Nome:</b>
  <%=h @pais.nome %>
</p>


<%= link_to 'Editar', edit_pais_path(@pais) %> |
<%= link_to 'Voltar', paises_path %>