config/routes.rb
Planarias::Application.routes.draw do
  get "exportar/alternativas_especies"

  resources :membros





  resources :artigos

  resources :alternativas

  resources :caracteristicas

  resources :especie_imagens

  resources :especies

  resources :municipios

  resources :estados

  resources :paises

  resources :alternativas_especies

  resources :verespecie

  resources :verespecie_imagem
  
  resources :usuarios

  resources :generos
  
  resources :familias
  
  resources :subfamilias  
  




  root :to => 'home#index'


  match ':controller(/:action(/:id(.:format)))'
end

app/models/familia.rb

class Familia < ActiveRecord::Base
  
  has_many :subfamilias
  has_many :generos, :through => :subfamilia

  validates :nome, :presence => true, :uniqueness => true
  
end

app/controllers/familias_controller.rb
# -*- encoding : utf-8 -*-
class FamiliasController < ApplicationController
  # GET /familias
  # GET /familias.xml
  def index
    @familias = Familia.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @familias }
    end
  end

  # GET /familias/1
  # GET /familias/1.xml
  def show
    @familia = Familia.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @familia }
    end
  end

  # GET /familias/new
  # GET /familias/new.xml
  def new
    @familia = Familia.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @familia }
    end
  end

  # GET /familias/1/edit
  def edit
    @familia = Familia.find(params[:id])
  end

  # POST /familias
  # POST /familias.xml
  def create
    @familia = Familia.new(params[:familia])

    respond_to do |format|
      if @familia.save
        flash[:notice] = 'Família foi criado(a) com sucesso.'
        format.html { redirect_to(@familia) }
        format.xml  { render :xml => @familia, :status => :created, :location => @familia }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @familia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /familias/1
  # PUT /familias/1.xml
  def update
    @familia = Familia.find(params[:id])

    respond_to do |format|
      if @familia.update_attributes(params[:familia])
        flash[:notice] = 'Família foi atualizado(a) com sucesso.'
        format.html { redirect_to(@familia) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @familia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /familias/1
  # DELETE /familias/1.xml
  def destroy
    @familia = Familia.find(params[:id])
    @subfamilias = @familia.subfamilias

    @destroyed = false
    if @subfamilias.first.nil?
      @familia.destroy
      @destroyed = true
    end

    respond_to do |format|
      if @destroyed
        flash[:notice] = 'Família excluído com sucesso.'
      else
        flash[:notice] = 'A família não pode ser excluído devido a relação com a subfamília ' + @subfamilias.first.nome
      end
      format.html { redirect_to(familias_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/familias_helper.rb
# -*- encoding : utf-8 -*-
module FamiliasHelper
end

app/views/familias/edit.html.erb
<h1>Editando família</h1>

<%= form_for(@familia) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.submit 'Atualizar' %>
  </p>
<% end %>

<%= link_to 'Ver', @familia %> |
<%= link_to 'Voltar', familias_path %>

app/views/familias/index.html.erb
<h1>Listando famílias</h1>

<% if @familias.size.zero? %>
  <br />
  <p> Nenhuma família cadastrada.</p>
<% else %>
<table>
  <tr>
    <th>Nome</th>
  </tr>

<% @familias.each do |familia| %>
  <tr>
    <td><%=h familia.nome %></td>
    <td><%= link_to 'Ver', familia %></td>
    <td><%= link_to 'Editar', edit_familia_path(familia) %></td>
    <td><%= button_to 'Excluir', familia, :confirm => 'Você tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%end%>
<br />

<%= link_to 'Criar família', new_familia_path %>

app/views/familias/new.html.erb
<h1>Nova família</h1>

<%= form_for(@familia) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.submit 'Criar' %>
  </p>
<% end %>

<%= link_to 'Voltar', familias_path %>

app/views/familias/show.html.erb
<p>
  <b>Nome:</b>
  <%=h @familia.nome %>
</p>


<%= link_to 'Editar', edit_familia_path(@familia) %> |
<%= link_to 'Voltar', familias_path %>