config/routes.rb
Planarias::Application.routes.draw do
  get "exportar/alternativas_especies"

  resources :membros





  resources :artigos

  resources :alternativas

  resources :caracteristicas

  resources :especie_imagens

  resources :especies

  resources :municipios

  resources :estados

  resources :paises

  resources :alternativas_especies

  resources :verespecie

  resources :verespecie_imagem
  
  resources :usuarios

  resources :generos
  
  resources :familias
  
  resources :subfamilias  
  




  root :to => 'home#index'


  match ':controller(/:action(/:id(.:format)))'
end

app/models/estado.rb
# -*- encoding : utf-8 -*-
class Estado < ActiveRecord::Base

  belongs_to :pais
  has_many :municipios

  validates :nome, :presence => true, :uniqueness => {:scope => :pais_id}
  validates :pais_id, :presence => true

  
end

app/controllers/estados_controller.rb
# -*- encoding : utf-8 -*-
class EstadosController < ApplicationController
  # GET /estados
  # GET /estados.xml
  def index
    @estados = Estado.find(:all, :include => [:pais], :order => "paises.nome ASC, estados.nome ASC")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.xml
  def show
    @estado = Estado.find(params[:id])
    @pais = Pais.find(@estado.pais_id)
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.xml
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.xml
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        flash[:notice] = 'Estado foi criado com sucesso.'
        format.html { redirect_to(@estado) }
        format.xml  { render :xml => @estado, :status => :created, :location => @estado }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @estado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.xml
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        flash[:notice] = 'Estado foi atualizado com sucesso.'
        format.html { redirect_to(@estado) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @estado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.xml
  def destroy
    @estado = Estado.find(params[:id])
    @municipios = @estado.municipios

    @destroyed = false
    if @municipios.first.nil?
      @estado.destroy
      @destroyed = true
    end

    respond_to do |format|
      if @destroyed
        flash[:notice] = 'Estado excluído com sucesso.'
      else
        flash[:notice] = 'O estado não pode ser excluído devido a relação com o município ' + @municipios.first.nome
      end
      format.html { redirect_to(estados_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/estados_helper.rb
# -*- encoding : utf-8 -*-
module EstadosHelper
end

app/views/estados/edit.html.erb
<h1>Editando estado</h1>

<%= form_for(@estado) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :pais_id %><br />
    <%= @paises = Pais.find(:all, :order => "nome" )
        f.collection_select(:pais_id, @paises, :id, :nome)%>
  </p>
  <p>
    <%= f.submit 'Atualizar' %>
  </p>
<% end %>

<%= link_to 'Ver', @estado %> |
<%= link_to 'Voltar', estados_path %>

app/views/estados/index.html.erb
<h1>Listando estados</h1>

<% if @estados.size.zero? %>
  <br />
  <p> Nenhum estado cadastrado.</p>
<% else %>
<table>
  <tr>
    <th>País</th>
    <th>Estado</th>
  </tr>

<% @estados.each do |estado| %>
  <tr>
    <td><%=h estado.pais.nome %></td>
    <td><%=h estado.nome %></td>
    <td><%= link_to 'Ver', estado %></td>
    <td><%= link_to 'Editar', edit_estado_path(estado) %></td>
    <td><%= button_to 'Excluir', estado, :confirm => 'Você tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%end%>
<br />

<%= link_to 'Criar estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>Criar estado</h1>

<%= form_for(@estado) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :pais_id %><br />
    <%= @paises = Pais.find(:all, :order => "nome" )
        f.collection_select(:pais_id, @paises, :id, :nome)%>
  </p>
  <p>
    <%= f.submit 'Criar' %>
  </p>
<% end %>

<%= link_to 'Votlar', estados_path %>

app/views/estados/show.html.erb
<p>
  <b>Nome:</b>
  <%=h @estado.nome %>
</p>

<p>
  <b>País:</b>
  <%=h @pais.nome %>
</p>


<%= link_to 'Editar', edit_estado_path(@estado) %> |
<%= link_to 'Voltar', estados_path %>